version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1693302010
layout:
  /header/:
    -
      - 'logo-1707 30'
      - 'spacer-7347 70'
  /main/:
    -
      - system-messages-5140
    -
      - system-content-1997
  /footer/:
    -
      - position-footer
    -
      - 'copyright-7204 40'
      - 'spacer-7757 30'
      - 'branding-3322 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
