name: 13
timestamp: 1693302010
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1693302010
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-5203: Menu
  sample:
    sample-1: 'Gantry 5'
    sample-2: 'Getting Started'
    sample-3: 'Key Features'
  messages:
    system-messages-8428: 'System Messages'
  position:
    position-footer: Footer
  copyright:
    copyright-6243: Copyright
  social:
    social-6139: Social
  branding:
    branding-5386: Branding
  mobile-menu:
    mobile-menu-9929: 'Mobile Menu'
inherit: {  }
