name: _body_only
timestamp: 1693315985
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1693302101
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-8619: 'System Messages'
  content:
    system-content-5889: 'Page Content'
inherit: {  }
