version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1693302101
layout:
  /header/:
    -
      - 'logo-9598 30'
      - 'spacer-4966 70'
  /navigation/:
    -
      - menu-5389
  /main/:
    -
      - system-content-7942
  /footer/:
    -
      - position-footer
    -
      - copyright-1902
  offcanvas:
    -
      - mobile-menu-2625
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
