name: _body_only
timestamp: 1693302010
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1693302010
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-8512: 'System Messages'
  content:
    system-content-3795: 'Page Content'
inherit: {  }
